name: Integration Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  # Permet de déclencher manuellement ce workflow
  workflow_dispatch:

jobs:
  testcontainers:
    name: Tests with Testcontainers
    runs-on: ubuntu-latest
    
    # Ces services ne sont pas nécessaires car les tests utilisent testcontainers
    # qui vont démarrer automatiquement les conteneurs Docker
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.x'

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Install dependencies
        run: go mod download

      - name: Run tests with Testcontainers
        run: go test ./... -v -timeout 180s
        env:
          # Nécessaire pour que testcontainers puisse utiliser le démon Docker
          TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: /var/run/docker.sock
          DOCKER_HOST: unix:///var/run/docker.sock